#!/usr/bin/env bash
set -e
if ! git diff --quiet || ! git diff --cached --quiet; then
  echo "Error: Uncommitted changes detected. Commit or stash them first."
  exit 1
fi
mise run check
echo "Bump version -> $*"
uv version --bump "$*"
version="v$(uv version --short)"
git add -A
git commit -m "chore: release $version"
git tag "$version"
git push && git push --tags
